// Zigbee
const SET_PRODUCTID = 'SET_PRODUCTID'
const SET_SERIALPORT = 'SET_SERIALPORT'
const SET_ZIGBEECONNECT = 'SET_CONNECT'

// Entity

const ADD_ENTITY = 'ADD_ENTITY'

// mqtt

const SET_MQTTSERVER = 'SET_MQTTSERVER'
const SET_MQTTCONNECT = 'SET_CONNECT'

module.exports = {
  SET_PRODUCTID: SET_PRODUCTID,
  SET_SERIALPORT: SET_SERIALPORT,
  SET_MQTTCONNECT: SET_MQTTCONNECT,
  SET_ZIGBEECONNECT: SET_ZIGBEECONNECT,
  SET_MQTTSERVER: SET_MQTTSERVER,
}
