const SET_PRODUCTID = 'SET_PRODUCTID'
const SET_SERIALPORT = 'SET_SERIALPORT'
const SET_CONNECT = 'SET_CONNECT'

module.exports = {
  SET_PRODUCTID: SET_PRODUCTID,
  SET_SERIALPORT: SET_SERIALPORT,
  SET_CONNECT: SET_CONNECT,
}
